// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CssTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "1c63270f-485d-4810-99b8-e9d9de82610c";
        public const string Name = "CSS Tools 2019";
        public const string Description = @"Provides additional features to the CSS editor in Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "css, less, sass, scss, stylesheet";
    }
}
